window:
  dynamic_padding: true
  decorations: none
  startup_mode: Maximized
font:
  size: 16.0
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic
draw_bold_text_with_bright_colors: true

# The definition of color schemes.
schemes:
  gruvbox_material_dark: &gruvbox_material_dark
    primary:
      background: '#282828'
      foreground: '#d4be98'

    normal:
      black:   '#282828'
      red:     '#ea6962'
      green:   '#a9b665'
      yellow:  '#d8a657'
      blue:    '#7daea3'
      magenta: '#d3869b'
      cyan:    '#89b482'
      white:   '#d4be98'

    bright:
      black:   '#282828'
      red:     '#ea6962'
      green:   '#a9b665'
      yellow:  '#d8a657'
      blue:    '#7daea3'
      magenta: '#d3869b'
      cyan:    '#89b482'
      white:   '#d4be98'
# }}}
# {{{ Gruvbox Mix Dark
  gruvbox_mix_dark: &gruvbox_mix_dark
    primary:
      background: '#282828'
      foreground: '#e2cca9'

    normal:
      black:   '#504945'
      red:     '#f2594b'
      green:   '#b0b846'
      yellow:  '#e9b143'
      blue:    '#80aa9e'
      magenta: '#d3869b'
      cyan:    '#8bba7f'
      white:   '#e2cca9'

    bright:
      black:   '#504945'
      red:     '#f2594b'
      green:   '#b0b846'
      yellow:  '#e9b143'
      blue:    '#80aa9e'
      magenta: '#d3869b'
      cyan:    '#8bba7f'
      white:   '#e2cca9'
# }}}
# {{{ Gruvbox Material Light
  gruvbox_material_light: &gruvbox_material_light
    primary:
      background: '#f2e5bc'
      foreground: '#654735'

    normal:
      black:   '#654735'
      red:     '#c14a4a'
      green:   '#6c782e'
      yellow:  '#b47109'
      blue:    '#45707a'
      magenta: '#945e80'
      cyan:    '#4c7a5d'
      white:   '#928374'

    bright:
      black:   '#654735'
      red:     '#c14a4a'
      green:   '#6c782e'
      yellow:  '#b47109'
      blue:    '#45707a'
      magenta: '#945e80'
      cyan:    '#4c7a5d'
      white:   '#928374'
# }}}
# {{{ Edge Light
  edge_light: &edge_light
    primary:
      background: '#fafafa'
      foreground: '#4b505b'

    normal:
      black: '#4b505b'
      red: '#d15b5b'
      green: '#608e32'
      yellow: '#be7e05'
      blue: '#5079be'
      magenta: '#b05ccc'
      cyan: '#3a8b84'
      white: '#dde2e7'

    bright:
      black: '#4b505b'
      red: '#d15b5b'
      green: '#608e32'
      yellow: '#be7e05'
      blue: '#5079be'
      magenta: '#b05ccc'
      cyan: '#3a8b84'
      white: '#dde2e7'
# }}}
# {{{ Edge Dark
  edge_dark: &edge_dark
    primary:
      background: '#2b2d37'
      foreground: '#c5cdd9'

    normal:
      black: '#3a3e4e'
      red: '#ec7279'
      green: '#a0c980'
      yellow: '#deb974'
      blue: '#6cb6eb'
      magenta: '#d38aea'
      cyan: '#5dbbc1'
      white: '#c5cdd9'

    bright:
      black: '#3a3e4e'
      red: '#ec7279'
      green: '#a0c980'
      yellow: '#deb974'
      blue: '#6cb6eb'
      magenta: '#d38aea'
      cyan: '#5dbbc1'
      white: '#c5cdd9'
# }}}
# {{{ Everforest Dark
  everforest_dark: &everforest_dark
    primary:
      background: '#2f383e'
      foreground: '#d3c6aa'

    normal:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'

    bright:
      black:   '#4b565c'
      red:     '#e67e80'
      green:   '#a7c080'
      yellow:  '#dbbc7f'
      blue:    '#7fbbb3'
      magenta: '#d699b6'
      cyan:    '#83c092'
      white:   '#d3c6aa'
# }}}
# {{{ Everforest Light
  everforest_light: &everforest_light
    primary:
      background: '#fdf6e3'
      foreground: '#5c6a72'

    normal:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'

    bright:
      black:   '#5c6a72'
      red:     '#f85552'
      green:   '#8da101'
      yellow:  '#dfa000'
      blue:    '#3a94c5'
      magenta: '#df69ba'
      cyan:    '#35a77c'
      white:   '#dfddc8'
# }}}
# {{{ Sonokai Default
  sonokai_default: &sonokai_default
    primary:
      background: '#2c2e34'
      foreground: '#e2e2e3'

    normal:
      black: '#181819'
      red: '#fc5d7c'
      green: '#9ed072'
      yellow: '#e7c664'
      blue: '#76cce0'
      magenta: '#b39df3'
      cyan: '#f39660'
      white: '#e2e2e3'

    bright:
      black: '#181819'
      red: '#fc5d7c'
      green: '#9ed072'
      yellow: '#e7c664'
      blue: '#76cce0'
      magenta: '#b39df3'
      cyan: '#f39660'
      white: '#e2e2e3'
# }}}
# {{{ Sonokai Shusia
  sonokai_shusia: &sonokai_shusia
    primary:
      background: '#2d2a2e'
      foreground: '#e3e1e4'

    normal:
      black: '#1a181a'
      red: '#f85e84'
      green: '#9ecd6f'
      yellow: '#e5c463'
      blue: '#7accd7'
      magenta: '#ab9df2'
      cyan: '#ef9062'
      white: '#e3e1e4'

    bright:
      black: '#1a181a'
      red: '#f85e84'
      green: '#9ecd6f'
      yellow: '#e5c463'
      blue: '#7accd7'
      magenta: '#ab9df2'
      cyan: '#ef9062'
      white: '#e3e1e4'
# }}}
# {{{ Sonokai Andromeda
  sonokai_andromeda: &sonokai_andromeda
    primary:
      background: '#2b2d3a'
      foreground: '#e1e3e4'

    normal:
      black: '#181a1c'
      red: '#fb617e'
      green: '#9ed06c'
      yellow: '#edc763'
      blue: '#6dcae8'
      magenta: '#bb97ee'
      cyan: '#f89860'
      white: '#e1e3e4'

    bright:
      black: '#181a1c'
      red: '#fb617e'
      green: '#9ed06c'
      yellow: '#edc763'
      blue: '#6dcae8'
      magenta: '#bb97ee'
      cyan: '#f89860'
      white: '#e1e3e4'
# }}}
# {{{ Sonokai Atlantis
  sonokai_atlantis: &sonokai_atlantis
    primary:
      background: '#2a2f38'
      foreground: '#e1e3e4'

    normal:
      black: '#181a1c'
      red: '#ff6578'
      green: '#9dd274'
      yellow: '#eacb64'
      blue: '#72cce8'
      magenta: '#ba9cf3'
      cyan: '#f69c5e'
      white: '#e1e3e4'

    bright:
      black: '#181a1c'
      red: '#ff6578'
      green: '#9dd274'
      yellow: '#eacb64'
      blue: '#72cce8'
      magenta: '#ba9cf3'
      cyan: '#f69c5e'
      white: '#e1e3e4'
# }}}
# {{{ Sonokai Maia
  sonokai_maia: &sonokai_maia
    primary:
      background: '#273136'
      foreground: '#e1e2e3'

    normal:
      black: '#1c1e1f'
      red: '#f76c7c'
      green: '#9cd57b'
      yellow: '#e3d367'
      blue: '#78cee9'
      magenta: '#baa0f8'
      cyan: '#f3a96a'
      white: '#e1e2e3'

    bright:
      black: '#1c1e1f'
      red: '#f76c7c'
      green: '#9cd57b'
      yellow: '#e3d367'
      blue: '#78cee9'
      magenta: '#baa0f8'
      cyan: '#f3a96a'
      white: '#e1e2e3'
# }}}
# {{{ Sonokai Espresso
  sonokai_espresso: &sonokai_espresso
    primary:
      background: "#312c2b"
      foreground: "#e4e3e1"

    normal:
      black: "#1f1e1c"
      red: "#f86882"
      green: "#a6cd77"
      yellow: "#f0c66f"
      blue: "#81d0c9"
      magenta: "#9fa0e1"
      cyan: "#f08d71"
      white: "#e4e3e1"

    bright:
      black: "#1f1e1c"
      red: "#f86882"
      green: "#a6cd77"
      yellow: "#f0c66f"
      blue: "#81d0c9"
      magenta: "#9fa0e1"
      cyan: "#f08d71"
      white: "#e4e3e1"
# }}}
# {{{ Soft Era
  soft_era: &soft_era
    primary:
      background: '#f9f5f5'
      foreground: '#be9898'

    normal:
      black: '#be9898'
      red: '#f165bd'
      green: '#96ad01'
      yellow: '#ec9157'
      blue: '#75a9d9'
      magenta: '#aea6e1'
      cyan: '#25b7b8'
      white: '#dfc5c5'

    bright:
      black: '#be9898'
      red: '#f165bd'
      green: '#96ad01'
      yellow: '#ec9157'
      blue: '#75a9d9'
      magenta: '#aea6e1'
      cyan: '#25b7b8'
      white: '#dfc5c5'
# }}}
colors: *sonokai_atlantis

background_opacity: .98
hide_when_typing: true

