window:
  dynamic_padding: true
  decorations: none
  startup_mode: Maximized
font:
  size: 16.0
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular
  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold
  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic
draw_bold_text_with_bright_colors: true

# The definition of color schemes.
schemes:
  monokai_pro: &monokai_pro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'
  
    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'
  
    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'
colors: *monokai_pro

background_opacity: 1
hide_when_typing: true

